version: '3.8'

services:
  # PostgreSQL Database
  database:
    image: postgres:15
    container_name: plant-tracker-db
    environment:
      POSTGRES_DB: plant_tracker
      POSTGRES_USER: plant_user
      POSTGRES_PASSWORD: plant_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/migrations:/docker-entrypoint-initdb.d
    restart: unless-stopped

  # Rust Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: plant-tracker-api
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://plant_user:plant_password@database:5432/plant_tracker
      PORT: 3000
      HOST: 0.0.0.0
      JWT_SECRET: your-super-secret-jwt-key-here
      CORS_ORIGIN: http://localhost:5173
      RUST_LOG: plant_tracker_api=debug,tower_http=debug
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      - database
    restart: unless-stopped

  # Frontend Development Server (Optional)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: plant-tracker-frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:3000/v1
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped

  # Database Administration (Optional)
  adminer:
    image: adminer
    container_name: plant-tracker-adminer
    ports:
      - "8080:8080"
    depends_on:
      - database
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  default:
    name: plant-tracker-network